# Generated by Django 5.1.3 on 2024-12-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dchoskzxj/image/upload/v1728892217/tsipho0ghipyymo9gs9s.webp', upload_to='images/'),
        ),
    ]
