# Generated by Django 5.1.3 on 2024-12-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../v1721986382/sample.jpg', upload_to='images/'),
        ),
    ]
