# Generated by Django 5.1.4 on 2024-12-28 11:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='v1734719974/hvc6gc5ikhagzoytuq3k', max_length=255, null=True, verbose_name='image'),
        ),
    ]
