# Generated by Django 5.1.3 on 2024-12-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../tsipho0ghipyymo9gs9s.webp', upload_to='images/'),
        ),
    ]
